notificationsInActionBar: false
disabledWorlds: []
debug: false
Language: English
DisableCreative: true
Timer:
  enable: false
  maxKills: 20
  resetTimeInSeconds: 30
dailylimit:
  enabled: false
  limit: 300
Entity:
  economy:
    elder_guardian: 1.0
    wither_skeleton: 1.0
    stray: 1.0
    husk: 1.0
    zombie_villager: 1.0
    skeleton_horse: 1.0
    zombie_horse: 1.0
    armor_stand: 1.0
    donkey: 1.0
    mule: 1.0
    evoker: 1.0
    vex: 1.0
    vindicator: 1.0
    illusioner: 1.0
    creeper: 1.0
    skeleton: 1.0
    spider: 1.0
    giant: 1.0
    zombie: 1.0
    slime: 1.0
    ghast: 1.0
    pig_zombie: 1.0
    enderman: 1.0
    cave_spider: 1.0
    silverfish: 1.0
    blaze: 1.0
    magma_cube: 1.0
    ender_dragon: 1.0
    wither: 1.0
    bat: 1.0
    witch: 1.0
    endermite: 1.0
    guardian: 1.0
    shulker: 1.0
    pig: 1.0
    sheep: 1.0
    cow: 1.0
    chicken: 1.0
    squid: 1.0
    wolf: 1.0
    mushroom_cow: 1.0
    snowman: 1.0
    ocelot: 1.0
    iron_golem: 1.0
    horse: 1.0
    rabbit: 1.0
    polar_bear: 1.0
    llama: 1.0
    parrot: 1.0
    villager: 1.0
  name:
    elder_guardian: elder_guardian
    wither_skeleton: wither_skeleton
    stray: stray
    husk: husk
    zombie_villager: zombie_villager
    skeleton_horse: skeleton_horse
    zombie_horse: zombie_horse
    armor_stand: armor_stand
    donkey: donkey
    mule: mule
    evoker: evoker
    vex: vex
    vindicator: vindicator
    illusioner: illusioner
    creeper: creeper
    skeleton: skeleton
    spider: spider
    giant: giant
    zombie: zombie
    slime: slime
    ghast: ghast
    pig_zombie: pig_zombie
    enderman: enderman
    cave_spider: cave_spider
    silverfish: silverfish
    blaze: blaze
    magma_cube: magma_cube
    ender_dragon: ender_dragon
    wither: wither
    bat: bat
    witch: witch
    endermite: endermite
    guardian: guardian
    shulker: shulker
    pig: pig
    sheep: sheep
    cow: cow
    chicken: chicken
    squid: squid
    wolf: wolf
    mushroom_cow: mushroom_cow
    snowman: snowman
    ocelot: ocelot
    iron_golem: iron_golem
    horse: horse
    rabbit: rabbit
    polar_bear: polar_bear
    llama: llama
    parrot: parrot
    villager: villager
BlockPayEntitiesSpawnedBy:
  NATURAL: false
  JOCKEY: false
  CHUNK_GEN: false
  SPAWNER: false
  EGG: false
  SPAWNER_EGG: false
  LIGHTNING: false
  BUILD_SNOWMAN: false
  BUILD_IRONGOLEM: false
  BUILD_WITHER: false
  VILLAGE_DEFENSE: false
  VILLAGE_INVASION: false
  BREEDING: false
  SLIME_SPLIT: false
  REINFORCEMENTS: false
  NETHER_PORTAL: false
  DISPENSE_EGG: false
  INFECTION: false
  CURED: false
  OCELOT_BABY: false
  SILVERFISH_BLOCK: false
  MOUNT: false
  TRAP: false
  ENDER_PEARL: false
  SHOULDER_ENTITY: false
  CUSTOM: false
  DEFAULT: false
